# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

    # Box
    config.vm.box = 'debian-8-amd64'

    # Network
    config.vm.network 'private_network', type: 'dhcp'

    # Providers
    config.vm.provider 'virtualbox' do |vb|
        vb.name   = 'debian-8-amd64'
        vb.memory = '1024'
        vb.gui    = false
        vb.customize ['modifyvm', :id, '--natdnshostresolver1', 'on']
        vb.customize ['modifyvm', :id, '--natdnsproxy1', 'on']
    end

    config.vm.provision 'ansible' do |ansible|
        ansible.playbook = 'ansible/playbook.yml'
        ansible.verbose  = false
        ansible.groups   = {'dev' => 'default'}
    end
end
