---

- hosts: all

  vars:

    # set by packer
    #_user: vagrant
    #_packer_builder: docker | virtualbox-iso

    ############
    # Timezone #
    ############

    elao_timezone: Etc/UTC

    #######
    # Apt #
    #######

    elao_apt_update: true

    elao_apt_repositories:
      - backports

    elao_apt_preferences:
      - git@backports
      - vim@backports

    elao_apt_packages: []

    ########
    # Sudo #
    ########

    elao_sudo_sudoers:
      - file: "{{ _user }}"
        config:
          - "{{ _user }} ALL=NOPASSWD:ALL"

    #########
    # Users #
    #########

    elao_users:
      - name:     "{{ _user }}"
        password: "{{ _user }}"
        # vagrant or docker password
        password: "{{ '$6$rounds=100000$57FvLCbisIN73c9g$EpejM4trTzJ0Tz9W1NIWVjm3S9TeZ2LOZflyQzGAl7CJi518st0kqfWO24SEKMQSdTG5GIu9IgaGmiFfFzA/51' if _user == 'vagrant' else '$6$rounds=100000$k85Toreb5r46eSdi$rPC1sKCeMMcF5bSrvVhuklK9eUMYnEhtSQv2.xqqI9Yx67eILmmlQSU2HhzzNO8VDyLZM0OcTVZ7GmVVs0TpQ0' }}"
        group:    users
        groups:   ['sudo']

    elao_users_authorized_keys:
      - user: "{{ _user }}"
        keys:
          - "{{ lookup('url', 'https://raw.githubusercontent.com/mitchellh/vagrant/master/keys/vagrant.pub') }}"

    #######
    # Git #
    #######

    elao_git_config_template: config/base.j2

    #############
    # Oh my zsh #
    #############

    elao_ohmyzsh_users:
      - user: "{{ _user }}"

    #######
    # Vim #
    #######

    elao_vim_config_template: config/base.j2

    ################
    # Alternatives #
    ################

    elao_alternatives:
      - name: editor
        path: "{{ elao_vim_bin }}"

  roles:
    - { role: elao.apt }
    - { role: elao.sudo }
    - { role: elao.users }
    - { role: elao.ssh }
    - { role: elao.zsh }
    - { role: elao.git }
    - { role: elao.ohmyzsh }
    - { role: elao.vim }
    - { role: elao.alternatives }
    - { role: elao.make }
