---

- hosts: all

  vars:

    _env:  dev

    # set by packer
    #_user: vagrant
    #_packer_builder: docker | virtualbox-iso

    ############
    # Timezone #
    ############

    elao_timezone: Etc/UTC

    #######
    # Env #
    #######

    elao_env:
      - SYMFONY_ENV: "{{ _env }}"

    #######
    # Apt #
    #######

    elao_apt_update: true

    elao_apt_repositories:
      - bearstech
      - backports
      - dotdeb
      #- dotdeb_php55
      - dotdeb_php56
      - nginx
      #- nodesource_0_10
      - nodesource_0_12
      #- postgresql

    elao_apt_preferences:
      - ruby@bearstech
      - git@backports
      - vim@backports
      - file: dotdeb
        template: preferences/dotdeb_low.j2
      - php@dotdeb
      #- mysql@dotdeb
      - nginx@nginx
      - nodejs@nodesource_0_12

    #######
    # Ssh #
    #######

    elao_ssh_config_sshd_template: config/sshd/{{ _env }}.j2

    elao_ssh_config_template: config/{{ _env }}.j2

    #######
    # Git #
    #######

    elao_git_config_template: config/{{ _env }}.j2

    #############
    # Oh my zsh #
    #############

    elao_ohmyzsh_users:
      - user:     "{{ _user }}"
        template: users/{{ _env }}.j2

    #######
    # Vim #
    #######

    elao_vim_config_template: config/{{ _env }}.j2

    #########
    # Files #
    #########

    elao_files:
      - path:  /var/log/symfony
        state: directory
        acls:
          - "user:{{ elao_php_user }}:rwx"
          - "user:{{ _user }}:rwx"
          - "default:user:{{ elao_php_user }}:rwx"
          - "default:user:{{ _user }}:rwx"
      - path:  /var/cache/symfony
        state: directory
        acls:
          - "user:{{ elao_php_user }}:rwx"
          - "user:{{ _user }}:rwx"
          - "default:user:{{ elao_php_user }}:rwx"
          - "default:user:{{ _user }}:rwx"

    #######
    # Gem #
    #######

    elao_gem_packages:
      - name:    capifony
        version: ~> 2.8

    #############
    # PhantomJS #
    #############

    elao_phantomjs_config_template: config/{{ _env }}.j2

    ###############
    # Mailcatcher #
    ###############

    elao_mailcatcher_config_template: config/{{ _env }}.j2

    ##########
    # Log.io #
    ##########

    elao_logio_config_harvester:
      - nodeName: App
      - logStreams:
        - php:
          - "{{ elao_php_log_dir }}/error.log"
        - nginx:
          - "{{ elao_nginx_log_dir }}/app.access.log"
          - "{{ elao_nginx_log_dir }}/app.error.log"
        - symfony:
          - /var/log/symfony/dev.log
          - /var/log/symfony/test.log
          - /var/log/symfony/prod.log

    #######
    # Php #
    #######

    elao_php_sapis: ['cli', 'fpm']

    elao_php_fpm_pools_exclusive: true
    elao_php_fpm_pools:
      - file:     www.conf
        template: fpm_pools/www_{{ _env }}.conf.j2

    elao_php_extensions:
      # Dev
      - xdebug
      # Symfony
      - intl
      - curl
      # App
      #- mysqlnd
      #- gd

    elao_php_configs_exclusive: true
    elao_php_configs:
      - file: 50-xdebug.ini
        template: configs/xdebug_{{ _env }}.ini.j2
      - file: 50-opcache.ini
        template: configs/opcache_{{ _env }}.ini.j2
      - file: 60-config.ini
        template: configs/{{ _env }}.ini.j2
        config:
          - date.timezone: UTC

    #########
    # Nginx #
    #########

    elao_nginx_config_template: config/http_{{ _env }}.conf.j2

    elao_nginx_configs_exclusive: true

    #######
    # Npm #
    #######

    elao_npm_packages:
      - name:    bower
        version: 1
      - name:    gulp
        version: 3

    ##############
    # Supervisor #
    ##############

    elao_supervisor_config_template: config/{{ _env }}.conf.j2

    elao_supervisor_configs_exclusive: true
    elao_supervisor_configs:
      - file:     inet-http-server.conf
        template: configs/inet_http_server_{{ _env }}.conf.j2

  roles:
    - { role: elao.timezone }
    - { role: elao.env }
    - { role: elao.apt }
    - { role: elao.ssh }
    - { role: elao.git }
    - { role: elao.zsh, when: "_packer_builder != 'docker'" }
    - { role: elao.ohmyzsh, when: "_packer_builder != 'docker'" }
    - { role: elao.curl }
    - { role: elao.vim, when: "_packer_builder != 'docker'" }
    - { role: elao.acl }
    - { role: elao.files }
    - { role: elao.make }
    - { role: elao.nodejs }
    - { role: elao.npm }
    - { role: elao.python, when: "_packer_builder != 'docker'" }
    - { role: elao.pip, when: "_packer_builder != 'docker'" }
    - { role: elao.ruby }
    - { role: elao.gem , when: "_packer_builder != 'docker'" }
    - { role: elao.phantomjs }
    - { role: elao.mailcatcher }
    - { role: elao.logio, when: "_packer_builder != 'docker'" }
    - { role: elao.php }
    - { role: elao.composer }
    - { role: elao.nginx }
    - { role: elao.supervisor, when: "_packer_builder != 'docker'" }
